### ISSUE TITLE
[FEATURE] Add depandabot

### ISSUE THREAD

**Issue by k-deepak04** [Fenrir-04/Algo-Media#104]
### Description

"Integrating Dependabot into our open-source project will automate dependency updates, ensuring we stay up-to-date with the latest security patches and feature enhancements."
"By leveraging Dependabot's automated pull requests for dependency updates, we can reduce the burden on maintainers and foster a more secure and stable codebase."
"Adding Dependabot as a dependency management tool will demonstrate our commitment to maintaining a healthy ecosystem, allowing contributors to focus on higher-value tasks while keeping our project dependencies secure and reliable."

### Screenshots

![image](https://github.com/Fenrir-04/Algo-Media/assets/96341431/10711f98-042c-4fb0-8d53-ae02ac0074d3)

**Comment by KOMALDEWNANI** [comment]
Are you a GSSOC'23 participant?

**Comment by k-deepak04** [comment]
yes
