### ISSUE TITLE
[FEATURE] Add close old issue bot

### ISSUE THREAD

**Issue by k-deepak04** [Fenrir-04/Algo-Media#105]
### Description

"By incorporating a bot that automatically closes old and inactive issues, we can ensure better issue management and keep the project organized."
"The bot's ability to identify and close outdated issues will streamline the issue tracking process, allowing the project team to focus on active and relevant tasks."
"Implementing an automated closing bot will help maintain a clean and up-to-date issue tracker, improving overall project efficiency and ensuring that active issues receive proper attention."

**Comment by KOMALDEWNANI** [comment]
How are you planning to do this?

**Comment by k-deepak04** [comment]
@KOMALDEWNANI there is bot i will just integrate that
and you can let me know how many days old issues it should close
usually it closes 30 days or more old issue
but it is customizable as per your need

**Comment by KOMALDEWNANI** [comment]
Ok, start working on it. 30 days time is fair enough
