### ISSUE TITLE
UI/UX issues, Limited Videos, Adding more topics

### ISSUE THREAD

**Issue by arnab-sur** [Fenrir-04/Algo-Media#11]
** Issues to be fixed
1. UI/UX issues : Adding a scrollbar to the topics lists to the left. Add theme changer (dark/light mode). fix the search section for smaller screen sizes
2. Limited videos : Everytime it shows only 5 videos. Let's switch it to unlimited videos and add previous/next page button in the lower portion of the page.
3. Add more topics : Add more genres/topics to get videos according to it.

** Hope project admin finds this useful, and help me by assigning this project to contribute in my GSSoC'23 journey. Thank You :)

**Comment by Fenrir-04** [comment]
Thanks for your feedback.
but the 1st point you mentioned is already assigned to someone else but you can start working on last two points.

**Comment by arnab-sur** [comment]
Thanks, Ok then I will go on with implementing those features.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Fenrir-04** [comment]
@arnab-sur hey what's the status about the issue ?
