### ISSUE TITLE
Adding Infinite Scroll in the feed and Progress bar

### ISSUE THREAD

**Issue by Piyush8172** [Fenrir-04/Algo-Media#112]
### Description

Currently a user can see only 5 video card so I want to add infinte scroll component so that many video cards could be seen this will enhance the user experience.

secondly, I would like to add progress bar.

**Comment by Piyush8172** [comment]
#112 Please assign me this issue. I have done this type of work in my project.

**Comment by KOMALDEWNANI** [comment]
Issue #95 is currently being addressed, and it pertains to the same matter.
