### ISSUE TITLE
[FEATURE]: Add Watchlist

### ISSUE THREAD

**Issue by suzy-g38** [Fenrir-04/Algo-Media#113]
### Description

If we have a feature like watchlist or save, that will be a great feature for the user.

### Additional information

I would like to work on it under GSSOC23.

**Comment by Visbhavesh** [comment]
please assign it to me and I will complete by tonight

**Comment by KOMALDEWNANI** [comment]
@suzy-g38, how are you planning to work on this?

**Comment by suzy-g38** [comment]
> @suzy-g38, how are you planning to work on this?

I am thinking of using localstorage to save them.

**Comment by KOMALDEWNANI** [comment]
What if the user wants to retrieve their saved playlist from a different browser or device?

**Comment by suzy-g38** [comment]
> What if the user wants to retrieve their saved playlist from a different browser or device?

That's not possible with the current structure because if I am not wrong, there is no server and database from which we can retrieve them. But If there is a complete backend section that I have missed, I will then make it completely backend driven...and we can add a lot of features just not only this watchlist.

**Comment by Fenrir-04** [comment]
@suzy-g38 you can start working on the with cache storage.

**Comment by suzy-g38** [comment]
> @suzy-g38 you can start working on the with cache storage.

okay
