### ISSUE TITLE
Bug: Subscribe button giving error

### ISSUE THREAD

**Issue by suzy-g38** [Fenrir-04/Algo-Media#114]
### Description

If you click on the subscribe button, it is giving error.

### Screenshots

Error from subscribe button

![image](https://github.com/Fenrir-04/Algo-Media/assets/62666287/c51b724f-ea1e-486b-9b4b-22a75c5379a9)
![image](https://github.com/Fenrir-04/Algo-Media/assets/62666287/31933aa0-62b2-44c3-a2e2-c889fe046519)

### Additional information

I would like to work on it under GSSOC'23

**Comment by Visbhavesh** [comment]
please assign it to me and I will complete by tonight

**Comment by suzy-g38** [comment]
Hey, @KOMALDEWNANI how do want the do this part? As the error is coming from the channelId part, as if you check the channelDetails part, there is nothing inside the id part.
![image](https://github.com/Fenrir-04/Algo-Media/assets/62666287/aedbcf29-14de-4dda-b019-c15bafad15b0)

![image](https://github.com/Fenrir-04/Algo-Media/assets/62666287/1aa52f59-c1c9-458e-9ac0-b537b37cb589)

So, how do you like me to proceed: 
1. Disable the subscribe button if there is no channelId inside id. 
2. Just leave the subscribe button as it is, and clicking on it will nothing happen at all.

Let me know what you choose.
