### ISSUE TITLE
Addition in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [Fenrir-04/Algo-Media#117]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes etc*

Please assign this issue to me under Gssoc'23 @Fenrir-04

**Comment by Fenrir-04** [comment]
hey @Anshika-Jain02, can you explain bit more about the template ?

**Comment by Anshika-Jain02** [comment]
@Fenrir-04 Sir, As i can see you have three issue templates present in your repository right now:- for bugs, for feature requests, and for document-related issues but I want to add one more issue template for guiding contributors who are working on style changes or UI of the website about different things they can specify while adding their own issue request.

**Comment by Fenrir-04** [comment]
@Anshika-Jain02 ok you can start working on it.
