### ISSUE TITLE
[GSSOC'23] Add a feature of BookMark the video

### ISSUE THREAD

**Issue by vivxsdb** [Fenrir-04/Algo-Media#127]
### Description

Actually I want to add a feature of bookmark the video so that the user can watch those videos later in future Can U please assign me this issue under GSSOC'23

**Comment by KOMALDEWNANI** [comment]
How are you planning to do that?

**Comment by vivxsdb** [comment]
Actually I want to provide login and sign up so that users can use this website and after I will storing the videos in the mongodb database . After storing the videos in the database every  video has a seperate I'd and I will storing the I'd of videos in user's schema

**Comment by Fenrir-04** [comment]
can we do it without using backend stuff ? @vivxsdb

**Comment by vivxsdb** [comment]
Actually we have to use backend for it

**Comment by vivxsdb** [comment]
Without that user can't be able to use ot
