### ISSUE TITLE
[GSSOC'23] Adding a download Feature 

### ISSUE THREAD

**Issue by vivxsdb** [Fenrir-04/Algo-Media#128]
### Description

Actually I want to add a download feature so that whenever a user has no internet connection they can see the videos which are downloaded can U assign me this feature under GSSOC'23

**Comment by Cipher-08** [comment]
Hey there , This Issue seems interesting to work on.
Please assign me this issue !!

**Comment by vivxsdb** [comment]
No, it's my idea

**Comment by Cipher-08** [comment]
😂😂No problem bruh 
Happy Coding

**Comment by Fenrir-04** [comment]
hey @vivxsdb, it's a nice idea, but where will you store these downloaded videos ? you will probably have to make a new column in sidebar for it and add the functionality.

**Comment by Fenrir-04** [comment]
@Cipher-08 @vivxsdb you both can work on the issue together, if it suits you.

**Comment by Cipher-08** [comment]
Ok , That would be good too!
Thank you

**Comment by Fenrir-04** [comment]
@Cipher-08 @vivxsdb are you guys working together or should i assign one of you ?

**Comment by vivxsdb** [comment]
Actually I am working on it but getting some confusion in it

**Comment by vivxsdb** [comment]
Please assign me @Fenrir-04

**Comment by Fenrir-04** [comment]
@vivxsdb you can clarify your doubts with mentors or with me if they're busy.

**Comment by vivxsdb** [comment]
So that I can ask my doubt

**Comment by Cipher-08** [comment]
@Fenrir-04 I can complete this task easily and I thought I have to do it in collaboration but no responses from the opposite sides ..
So I started working on it 
Please assign this task to me
