### ISSUE TITLE
[GSSOC'23] Adding Login and SignUp feature

### ISSUE THREAD

**Issue by vivxsdb** [Fenrir-04/Algo-Media#142]
### Description

Actually I want to provide login and sign up feature so that the users and use your website and using login and sign up we can implement advance functionalities as well Can u please assign this issue under gssoc'23

**Comment by Harry262530** [comment]
hello, I would like to contribute on this project, Kindly assign it to me

**Comment by vivxsdb** [comment]
No, It's is my issue

**Comment by vivxsdb** [comment]
Please assign me this issue

**Comment by Fenrir-04** [comment]
how will you work on the login and signup feature ?

**Comment by vivxsdb** [comment]
Actually I thought that login and sign up is not implemented but later while gone through the issue I recognised that it is was already implemented
