### ISSUE TITLE
Adding bright mode to your website and make navbar more beautiful 

### ISSUE THREAD

**Issue by Divyanshu24** [Fenrir-04/Algo-Media#147]
### Description

I can add bright mode to your website and also make navbar attractive

**Comment by Fenrir-04** [comment]
what do you mean by bright mode ? like it will brighten the screen or change the dark mode ?

**Comment by Divyanshu24** [comment]
Bright mode means like in websites you have seen that there have two mode bright and dark mode in which user can switch between them by clicking button. 
I can add button so that user can switch to bright or dark mode according to there preference.
