### ISSUE TITLE
[Bug]: Search bar is not working properly

### ISSUE THREAD

**Issue by suzy-g38** [Fenrir-04/Algo-Media#149]
### Description

If you search something at the home page it is working fine, but if you search afterward, it is not showing the data. After refreshing the page it is showing correct data.

### Screenshots

![image](https://github.com/Fenrir-04/Algo-Media/assets/62666287/7d7116b5-cb11-44df-bd1c-92805eb19a11)

### Additional information

I would like to work on it under gssoc23

**Comment by KHADIJA-09** [comment]
Please assign this task to fix the bug.

**Comment by Nishitbaria** [comment]
hey @KHADIJA-09  please assign me to this issue I can do this in one day

**Comment by LaxmanSingh07** [comment]
hey @Fenrir-04  is this issue has resolved?
if not, Please Assign me the task under GSSOC'23. I am eager to work on it.
