### ISSUE TITLE
Addition of an Manga and Comic section.

### ISSUE THREAD

**Issue by Pin4sf** [Fenrir-04/Algo-Media#15]
# Overview

There should be a section dedicated to Comics and Mangas which will help to diversify the userbase who like to read manga and comic.
This will also increase the media coverage apart from videos.

<hr>

## Advantages of this proposal
- Platform will have all in one media content.
- This will help gain more user who are anime/manga fans.
- Comic will gain more users who like DC and Marvel.

> I would Also add a download function which will allow user to have offline reading experience.

**Comment by Pin4sf** [comment]
Also while clicking on logo the page is not going on home page i would like to fix that too.

**Comment by Fenrir-04** [comment]
You can start working on the Comic section for DC, marvel and manga.
