### ISSUE TITLE
[FEATURE] Add Important checkboxes in the issue template

### ISSUE THREAD

**Issue by parasss19** [Fenrir-04/Algo-Media#155]
## Current 
- There are no checkboxes in the issue template
- During labeling its difficult for project admins to label the issues 
- Sometimes contributor also forget to label like (GSSOC'23)

## Change 
- I will add important checkboxes in the issue template so that it would be easy for contributror and project admin to label the issues

### Screenshots

<img width="640" alt="Screenshot 2023-06-20 233055" src="https://github.com/Fenrir-04/Algo-Media/assets/101205226/6f228ab4-7971-4ea3-9799-a1e539cbd588">

**Comment by KHADIJA-09** [comment]
Please assign me this task.
