### ISSUE TITLE
[Feature-request]Show publishedAt or duration from day of published

### ISSUE THREAD

**Issue by ahegde3** [Fenrir-04/Algo-Media#16]
In the current UI there is no information of when the video was published.It would be helpful to user to know the date of publication. The API provides publishedAt data.

Let me know do you want to include this feature .

Please assign me this issue under GSSOC'23

**Comment by Fenrir-04** [comment]
Thanks for the feedback.
the feature you mentioned sounds good.
you can start working on it.
