### ISSUE TITLE
[Style Change] Balance dark and light element in login and signup page

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Fenrir-04/Algo-Media#166]
### Description

Currently, the color combination of the signup and login page is too dark as shown below.

<img width="960" alt="1" src="https://github.com/Fenrir-04/Algo-Media/assets/86224794/f0492f98-ab72-455b-be0b-22d6a6152dbd">

 All the elements on this page have color properties that are in the dark color category. This reduces the contrast, visibility, and readability of the page. I want to change the color of the form fields and display the form as a card which will balance the dark and light elements of the page. Also, add some other changes which will increase the contrast of both of these pages.

Normally, it is recommended to display light elements on dark background and dark elements on light background, I will use this principle and make the page more visually appealing to users.

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by AlfiyaSiddique** [comment]
@Fenrir-04 This is the changed UI of signup/login form
How's it?

![1](https://github.com/Fenrir-04/Algo-Media/assets/86224794/29cfc61e-8778-47c8-9030-c5108ee6eda2)

If you want me to chnage or add anything, then please let me know

**Comment by Fenrir-04** [comment]
hey @AlfiyaSiddique nice work, but i think the color contrast is a bit too much, so instead of white can we make it a more easy-on-the-eyes colour like the github sign up page ? 
do tell me what you think.

**Comment by AlfiyaSiddique** [comment]
> hey @AlfiyaSiddique nice work, but i think the color contrast is a bit too much, so instead of white can we make it a more easy-on-the-eyes colour like the github sign up page ? do tell me what you think.

Oh okay, Got you. Will share a new design by taking references from GitHub!
Also, the black background color of this site is too black which is normally not considered a good color for huge background. So can we change it to a slightly less dark black one?
Do let me know your opinion

**Comment by Fenrir-04** [comment]
nice work @AlfiyaSiddique 
1st color combination looks better imo.
How about we change the black screen with a dark grey kind color or something matching with the smaller sign up portion in the 1st ?
Do tell me what you think :)
