### ISSUE TITLE
[FEATURE] Add label issues yml file

### ISSUE THREAD

**Issue by Abhinavcode13** [Fenrir-04/Algo-Media#176]
### Description

.

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Fenrir-04** [comment]
what exactly you want to do ? explain briefly.

**Comment by Fenrir-04** [comment]
@Abhinavcode13
