### ISSUE TITLE
Unhandled promise

### ISSUE THREAD

**Issue by debankanmitra** [Fenrir-04/Algo-Media#177]
### Description

![Screenshot from 2023-07-13 14-21-48](https://github.com/Fenrir-04/Algo-Media/assets/41522827/357a5962-ac06-4f3b-b85c-ec1dbf8eda57)

### Additional information

can i work on this issue?

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Fenrir-04** [comment]
what will change after you handle these promises ? @debankanmitra

**Comment by debankanmitra** [comment]
the error coming through sonarlint won't come , code will be more clean and readable ...

**Comment by Fenrir-04** [comment]
@debankanmitra ok you can start then.
