### ISSUE TITLE
[FEATURE] Make the color of scroll to top button matching with the theme of website

### ISSUE THREAD

**Issue by sumitkr2000** [Fenrir-04/Algo-Media#178]
### Description

Hwy @Fenrir-04 The color of scroll to top button does not match the theme of the website. Due to this, it is not looking good. Please assign me this issue. Thank you!

### Screenshots

![image](https://github.com/Fenrir-04/Algo-Media/assets/100675296/a5daeecc-05e7-4bca-9fd8-6460552781dd)

### Additional information

If the button is red it would be much more appealing.

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Codename-shaShank** [comment]
Hello @Fenrir-04 I think I can help with this please assign this to me.Thank you : )
