### ISSUE TITLE
Different Icons for languages in SideBar

### ISSUE THREAD

**Issue by muhammedanaskhan** [Fenrir-04/Algo-Media#18]
![req](https://github.com/Fenrir-04/Algo-Media/assets/72510634/1b699342-7a99-4363-8189-730c0d1499c7)

Adding respective icons for js, React, Next will improve the UI a bit, please allow me to work on this and assign the task as well..

**Comment by Fenrir-04** [comment]
Go ahead.

**Comment by muhammedanaskhan** [comment]
hey @Fenrir-04 some icons are not available on mui so can I add directly the png files in public folder...?
