### ISSUE TITLE
 Feature: Auto issue assign

### ISSUE THREAD

**Issue by andoriyaprashant** [Fenrir-04/Algo-Media#180]
### Description

By implementing the Auto Issue Assignment feature using GitHub Actions, the issue assignment process becomes automated and efficient. Issues matching specific comment-based criteria will be automatically assigned to the user who made the relevant comment, improving collaboration and task management within the repository.

## Implementation:

.github\workflow

### Screenshots

![Screenshot 2023-07-13 234416](https://github.com/Fenrir-04/Algo-Media/assets/121665385/f785e6fa-f4df-47a5-9dbb-6c03d3635cec)

### Additional information

GSSOC 2023

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by andoriyaprashant** [comment]
Hey @Fenrir-04 Please review my pull request #181 
Thank you

**Comment by Fenrir-04** [comment]
Hey @andoriyaprashant I haven't still assigned the issue to anyone so why are you doing PR's ?

**Comment by andoriyaprashant** [comment]
Sorry @Fenrir-04 , from now on, I will keep this in mind. But could you check out my pull request, please
Thank you.
