### ISSUE TITLE
[FEATURE] Improve Sign in and Sign up page

### ISSUE THREAD

**Issue by rishuraj1** [Fenrir-04/Algo-Media#184]
### Description

We might need to improve the UI  of Sign in page and sign up page for better user experience.
We can add more icons instead of just text to provide a better user interface for the user.
Also, we need to hide the search bar when in sign in or sign up page.

Please asssign this task to me under GSSoC '23. Thank You!

### Screenshots

<img width="959" alt="image" src="https://github.com/Fenrir-04/Algo-Media/assets/47839626/506b2626-7bc7-4c18-a162-68e4397524b4">

![image](https://github.com/Fenrir-04/Algo-Media/assets/47839626/9af3132a-35f1-4f77-9106-bbe041a9cf83)

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Fenrir-04** [comment]
@rishuraj1 explain briefly about the designs or icons you have in mind.

**Comment by rishuraj1** [comment]
@Fenrir-04  about the functionality, we can implement we can implement Google's OAuth for automatic login,
- I do believe that there is no need of search bar in the login/signup page.
- The whole signin/signup form should be in a container div with modern design. On the left part of which will be OAuth or/and image.

eg: something like this.
<img width="542" alt="image" src="https://github.com/Fenrir-04/Algo-Media/assets/47839626/ec9a496e-ad9a-4a25-9fff-ffbd4c97bce5">
