### ISSUE TITLE
[FEATURE]  Center the search bar

### ISSUE THREAD

**Issue by rishuraj1** [Fenrir-04/Algo-Media#185]
### Description

For better user experience and interface of app we should center the search bar which is currently placed in the end of header.
Also, add some styles.

Please assign this task to me under GSSoC '23. Thank You !

### Screenshots

current:
![image](https://github.com/Fenrir-04/Algo-Media/assets/47839626/043110d7-d3fd-4ef0-95f7-a003bb979117)

proposed idea:
![image](https://github.com/Fenrir-04/Algo-Media/assets/47839626/12712584-4723-428c-b1ca-dc2bc4507a67)

### Checklist

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Fenrir-04** [comment]
hey @rishuraj1, aside from the searchbar, what other designs do you have in mind ? Please explain brifly.
