### ISSUE TITLE
Want to Improve Individual  Video Page 

### ISSUE THREAD

**Issue by sujitmemane** [Fenrir-04/Algo-Media#23]
Hello, Sir! 👋🏼

I am [Sujit Memane](https://thesujitmemane.vercel.app/), a front-end React developer with expertise in creating visually stunning user interfaces. I have a strong portfolio that showcases my past work, highlighting my skills and abilities in designing attractive UIs.

I would be thrilled to contribute to the improvement of your Video Page. Please consider assigning this issue to me, as it would be my pleasure to work on it and bring my expertise to create a better Video Page. I have made a similar project, you can view it 

Looking forward to the opportunity!

Porrtfolio Link : https://thesujitmemane.vercel.app/
Youtube Clone  Project : https://youtube-clone-sam.vercel.app/

**Comment by Fenrir-04** [comment]
Thanks for your feedback.
I saw your YT clone and it does looks amazing, unfortunately, the UI improvement has been assigned to someone else.
