### ISSUE TITLE
[BUG] Improve the click accuracy

### ISSUE THREAD

**Issue by ahegde3** [Fenrir-04/Algo-Media#27]
There is an issue with the click.When I click on the lower part of the thumbnail it takes me to channel information. As a user I would prefer it should redirect to the video and only when I am specifically clicking the channel name it should take to channel info page.

Let me know do you want to fix this

Please assign me this issue under GSSOC'23

**Comment by Fenrir-04** [comment]
thanks for your feedback.
you can start working on this bug.
