### ISSUE TITLE
[ Feature ] Add a login page 

### ISSUE THREAD

**Issue by AKACHI-4** [Fenrir-04/Algo-Media#28]
Hey 👋, I am a Gssoc'23 contributor 

Feature
---
I would like to add a login page for your YouTube clone so it become personalized for every user. 

> **Kindly assign it to me under _GSSOC'23_** 
> **I will surely complete it ASAP**

**Comment by Fenrir-04** [comment]
This feature is already assigned to someone else.
Thanks

**Comment by AKACHI-4** [comment]
Okay no problem thanks
