### ISSUE TITLE
Improve Landing Page UI with additional Features [GSSOC'23]

### ISSUE THREAD

**Issue by CodeMaster17** [Fenrir-04/Algo-Media#3]
I went through your websites and there are number of mistakes, and there are number of ways in which it can be corrected.
Here are the features I can provide: 
- Improved Search Bar and its functionality 
- Improved UI  
- Login Logout Functionality

Allow me to this under GSSOC'23

**Comment by Fenrir-04** [comment]
Thank you for taking the time to review my website and providing valuable feedback. I appreciate your attention to detail and your willingness to help enhance the platform.

Best regards,
#GSSOC23
Harshvardhan singh

**Comment by Fenrir-04** [comment]
Regarding that login and logout functionality, will you also be adding sign up feature too ?

**Comment by CodeMaster17** [comment]
Yess

**Comment by Fenrir-04** [comment]
Good.
