### ISSUE TITLE
Add a scroll to top navigation button

### ISSUE THREAD

**Issue by abhinav-m22** [Fenrir-04/Algo-Media#31]
There is an absence of a scroll-to-top button on the website. The website's user experience would be improved by the addition of this floating button.
Due to my prior experience in building for personal projects, I'd like to contribute this feature.

Please assign me the task under GSSoC'23.

**Comment by Sandeep0306** [comment]
Hii, I want to add scroll to top button which will be better for the user to navigate to top of the page. Please assign me this issue under Gssoc'23

**Comment by yashvardhan-verma** [comment]
@abhinav-m22 please start working on this issue.

**Comment by abhinav-m22** [comment]
I've added a PR - #50 
Please have a look.
