### ISSUE TITLE
we can add a live link 

### ISSUE THREAD

**Issue by codewithnadeem14502** [Fenrir-04/Algo-Media#37]
hello sir. i have already deploy  some of my project and it is good to have a live link. it will have a good impression . hope you assign me this issue . happy to work with you

**Comment by codewithnadeem14502** [comment]
shall i start the work ?

**Comment by Fenrir-04** [comment]
hey @codewithnadeem14502 the site is already deployed on netlify, will you be deploying such that the changes in main is reflected live on the site ?
