### ISSUE TITLE
we can add some better UI for channel page

### ISSUE THREAD

**Issue by codewithnadeem14502** [Fenrir-04/Algo-Media#38]
![bg](https://github.com/Fenrir-04/Algo-Media/assets/105824474/72c0a1e5-3a1f-47f1-a6a3-775676913625)

i think it look so simple here. we can add some gradient colors. i will improve the user experience so i request you to assign me this issue . happy to work with you

**Comment by abhiraj-ku** [comment]
Hey is this issue assigned to someone , I want to work on this issue
