### ISSUE TITLE
IMPROVE THE REAME OF THE PAGE 

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [Fenrir-04/Algo-Media#4]
I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

**Comment by Ayush-Tibrewal** [comment]
@Fenrir-04 HELLO PLEASE ASSIGN WITH THE ISSUE

**Comment by Fenrir-04** [comment]
I can't see any changes in the Readme

**Comment by Ayush-Tibrewal** [comment]
assign me i will make the changes

**Comment by Ayush-Tibrewal** [comment]
please add GSSOC label then only it will  count under GSSOC

**Comment by Fenrir-04** [comment]
Hey! what's the status about the README.

**Comment by Ayush-Tibrewal** [comment]
@Fenrir-04 I will make the pull request done with task but please make it under gssoc first 
add gssoc label

**Comment by Ayush-Tibrewal** [comment]
@Fenrir-04 making pull requesting in 5mins

**Comment by Ayush-Tibrewal** [comment]
@Fenrir-04 done with the changes please let me known if you have any problem.
