### ISSUE TITLE
video cards look so simple?

### ISSUE THREAD

**Issue by codewithnadeem14502** [Fenrir-04/Algo-Media#46]
i think we can add the some more styling to video card's and i request you to assign me this issue . i will happy to wok with you

**Comment by codewithnadeem14502** [comment]
shall i start the work ?

**Comment by KOMALDEWNANI** [comment]
Go ahead!

**Comment by utkarshgupta04092003** [comment]
Hello @KOMALDEWNANI ,
I also want to work on this issue, video cards are soo simple, and I want to make it more interactive.
Can you please assign it me too

**Comment by KOMALDEWNANI** [comment]
You can work with @codewithnadeem14502 to make it more visually appealing and interactive.

**Comment by utkarshgupta04092003** [comment]
@KOMALDEWNANI I have committed and made a pull request, please review it and give your suggestion.
