### ISSUE TITLE
channel page can be improve ?

### ISSUE THREAD

**Issue by codewithnadeem14502** [Fenrir-04/Algo-Media#47]
i think we have some styling to the channel page.  and i request you to assign me this issue . i will happy to wok with you

![channel](https://github.com/Fenrir-04/Algo-Media/assets/105824474/58345605-8785-40ff-b52d-db832359b469)

**Comment by yashvardhan-verma** [comment]
@codewithnadeem14502 Please elaborate what will you like to add.

**Comment by codewithnadeem14502** [comment]
like we can changes simple subscribers to background color to like with some border radius, here is just an example see this 
![chnnel](https://github.com/Fenrir-04/Algo-Media/assets/105824474/df0f729e-4d3e-420c-9704-b971ad2c58ce)
so can you assign me this.

**Comment by yashvardhan-verma** [comment]
okay, @codewithnadeem14502 start working on this issue.

**Comment by codewithnadeem14502** [comment]
thank you so much for assign me sir, soon i will update you

**Comment by codewithnadeem14502** [comment]
sir please have a look on my PR . 
final look of our site 
![sub](https://github.com/Fenrir-04/Algo-Media/assets/105824474/9b560838-0718-4190-8fba-7fbe93392d2a)

**Comment by codewithnadeem14502** [comment]
Any update sir

**Comment by codewithnadeem14502** [comment]
i have successfully and raise a PR please have  a  look

**Comment by codewithnadeem14502** [comment]
Thank u
