### ISSUE TITLE
Hover effect on Video Card [GSSoC'23]

### ISSUE THREAD

**Issue by ruturajpatra99** [Fenrir-04/Algo-Media#49]
I want to add hover effect on video cards. Please assign me to contribute on this issue.⭐

**Comment by yashvardhan-verma** [comment]
@ruturajpatra99 Do you mean preview on hover ?

**Comment by ruturajpatra99** [comment]
> @ruturajpatra99 Do you mean preview on hover ?

I mean by text highlighting and transform scaling as we hover on card.

**Comment by yashvardhan-verma** [comment]
Okay you can start working on this. And also give yourself a try to add preview feature too.
We will help you through

**Comment by ruturajpatra99** [comment]
> Okay you can start working on this. And also give yourself a try to add preview feature too. We will help you through

Sure I'll give a try

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by yashvardhan-verma** [comment]
@ruturajpatra99 are you working on this issue or should I assign @sagnik-p to this issue?

**Comment by ruturajpatra99** [comment]
> @ruturajpatra99 are you working on this issue or should I assign @sagnik-p to this issue?

I'm willing to working on new issue, you can assign this to @sagnik-p
