### ISSUE TITLE
Refactor ChannelDetail and VideoDetail

### ISSUE THREAD

**Issue by kailashchoudhary11** [Fenrir-04/Algo-Media#53]
We can refactor the ChannelDetail and VideoDetail components to use loaders.

**Comment by KOMALDEWNANI** [comment]
Could you describe more clearly what exactly are you trying to do?

**Comment by kailashchoudhary11** [comment]
> Could you describe more clearly what exactly are you trying to do?

As of now, we are fetching data using the `useEffect` hook. Instead, we can fetch data using the loader function. You can see the Feed component for reference. @KOMALDEWNANI
