### ISSUE TITLE
Error Page

### ISSUE THREAD

**Issue by ahegde3** [Fenrir-04/Algo-Media#57]
Route to an error page which will convey the site is not available at the moment. For any api related error we can route to this page.

Let me know do you want to include this feature .

Please assign me this issue under GSSOC'23

**Comment by yashvardhan-verma** [comment]
Nice idea @ahegde3 , make separate pages for 404 and api realted issue

**Comment by PatilHarshh** [comment]
hi @yashvardhan-verma  i am intrested to do it so please assign me

**Comment by ahegde3** [comment]
@PatilHarshh may be we can collaborate. You can make the UI and I can handle the routing and error boundary.

**Comment by PatilHarshh** [comment]
@ahegde3 That will great idea. Please tell @yashvardhan-verma  to assign me as well.

**Comment by PatilHarshh** [comment]
![Screenshot (61)](https://github.com/Fenrir-04/Algo-Media/assets/120102234/05d33ebe-7361-43b2-9c35-201d3474c227)
is it ok @ahegde3  and @yashvardhan-verma

**Comment by yashvardhan-verma** [comment]
Looks good to me, you and @ahegde3 can work collaboratively, When you both area done create a PR and mark that as done.
