### ISSUE TITLE
feat: User authentication

### ISSUE THREAD

**Issue by SINJINI-G** [Fenrir-04/Algo-Media#6]
I will make a signup component for users to create new user account.

Can you please assign this issue to me for gssoc 2023? @Fenrir-04

**Comment by ayesha-firdaus** [comment]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by Fenrir-04** [comment]
Thanks for your feedback.
But this issue is already assigned to someone else.
