### ISSUE TITLE
we can change the background color to more interesting 

### ISSUE THREAD

**Issue by codewithnadeem14502** [Fenrir-04/Algo-Media#60]
![Screenshot 2023-05-23 234234](https://github.com/Fenrir-04/Algo-Media/assets/105824474/cf11b541-c81e-4deb-a75b-a8f9f9ffc0b4)

i have some thing special for this . hope you understand and assign me this issue i will happy to  work with you

**Comment by yashvardhan-verma** [comment]
sure @codewithnadeem14502 start working on this.

**Comment by codewithnadeem14502** [comment]
thank you
