### ISSUE TITLE
Redesign the navbar

### ISSUE THREAD

**Issue by abhinav-m22** [Fenrir-04/Algo-Media#64]
As seen in the image below, the navbar looks pretty empty...

<img width="959" alt="image" src="https://github.com/Fenrir-04/Algo-Media/assets/113239388/6ff1b969-532f-404d-9849-24ec478d6a7e">

A brand name can be added near the logo, the search bar can be centered at the div and some additional icons can be added just like the actual YouTube web page as shown below:

<img width="958" alt="image" src="https://github.com/Fenrir-04/Algo-Media/assets/113239388/a8680623-cb8d-4ff7-a6ba-dcad90257283">

Profile icon, Notification icon, microphone icon can be added to make the navbar look filled with a lot of components.

I would like to work on this feature.
Please assign me the task under GSSoC'23.

**Comment by Fenrir-04** [comment]
Hello @abhinav-m22, in the navbar will you only be adding components for looks only or will they be functional as well ?

**Comment by abhinav-m22** [comment]
> Hello @abhinav-m22, in the navbar will you only be adding components for looks only or will they be functional as well ?

At first I'll add only the icons for a better visual look. And then I'll add some funciotnalities if possible..

**Comment by abhinav-m22** [comment]
Hey @Fenrir-04 ..
Any update about the issue? Should I work on it?

**Comment by Fenrir-04** [comment]
@abhinav-m22 yes you can start working on the issue

**Comment by Neha5679** [comment]
I would like to work on it. Please assign me
