### ISSUE TITLE
[GSSOC'23]Want To add responsive footer of Algo-Media

### ISSUE THREAD

**Issue by piyush-mahajan** [Fenrir-04/Algo-Media#66]
The footer is the very main feature for user convenience and user flow of the site as we reduce the device screen it becomes very convenient for a user to navigate different pages of the site and also wants to fix the issue of different sizes of div which makes the site very out of touch, can you assign it to me?
![media](https://github.com/Fenrir-04/Algo-Media/assets/98900169/5cb03463-808c-4353-834d-4609d1db92c1)

**Comment by chiki012** [comment]
Hello, I'm good at frontend development, I can add more features and functionalities. please assign me this issue.
I'm GSSOC'23 contributor.

**Comment by Fenrir-04** [comment]
Hello @chiki012 can specify what kind of features you're talking about ?

**Comment by chiki012** [comment]
@Fenrir-04 Hello, I can modify it with animation, adding the proper hovering, with linking pages. also can add social media links and Important contact information with good animation and styling. Also, add some more attractive things.
