### ISSUE TITLE
feat: User login

### ISSUE THREAD

**Issue by SINJINI-G** [Fenrir-04/Algo-Media#7]
I will make the login page for users to login after signup.

Can you please assign this issue to me for gssoc 2023? @Fenrir-04

**Comment by Uma-Shankar0927** [comment]
@Fenrir-04  I am proficient in MERN stack technology. I can handle this issue. Please assign me the task.

**Comment by Fenrir-04** [comment]
I have already assigned this issue to someone else. 
Thanks.
