### ISSUE TITLE
Adding Tech Stacks Used in ReadMe Section

### ISSUE THREAD

**Issue by abhi03ruchi** [Fenrir-04/Algo-Media#70]
I want to add Technology Stack used in the ReadMe. This would be quite helpful for contributors who are looking forward to contributing to the site.

This would enhance the readMe section.
Plz, assign me this task.

**Comment by niveditavb05** [comment]
I would like to take on the task of adding the tech stacks used in the ReadMe section of our project. I am confident in my ability to complete this task accurately and efficiently. By assigning this task to me, I will ensure that the ReadMe section reflects the most up-to-date information, providing a valuable resource for external stakeholders. Please consider assigning me this task.

**Comment by abhi03ruchi** [comment]
Hi , @KOMALDEWNANI, I have created a pr, please review and merge it.
