### ISSUE TITLE
Missing Issue Template in Repository

### ISSUE THREAD

**Issue by Nishitbaria** [Fenrir-04/Algo-Media#71]
**Description:**

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

**Comment by yashvardhan-verma** [comment]
nice @Nishitbaria starting working on this issue

**Comment by Nishitbaria** [comment]
I have solved the issue and created a pull request. Now, you can proceed to merge it. : https://github.com/Fenrir-04/Algo-Media/pull/75
