### ISSUE TITLE
[FEATURE] Add Voice Search

### ISSUE THREAD

**Issue by kartikayasija** [Fenrir-04/Algo-Media#83]
### Description

Implementing Search by Voice Feature

Like this
<img width="634" alt="image" src="https://github.com/Fenrir-04/Algo-Media/assets/115306535/8d46e093-d120-493e-bc86-d6afb7c5cc17">

### Screenshots

<img width="634" alt="image" src="https://github.com/Fenrir-04/Algo-Media/assets/115306535/c1d623ef-5ab4-4b7c-80c1-a1ae3ca016e6">

**Comment by KOMALDEWNANI** [comment]
Great idea! Go ahead 🚀

**Comment by kartikayasija** [comment]
Thanks @KOMALDEWNANI
