### ISSUE TITLE
Header UI update with new logo andimporoved search bar

### ISSUE THREAD

**Issue by KashiwalHarsh** [Fenrir-04/Algo-Media#86]
### Description

I Want to work on this issue under GSSOC '23

Changes I want to propose for this project are - 

- The name of the website/project is not displayed alongside the log
- search bar does not follow the basic UI rules and looks distinct 
- alignment of the search bar is not proper with the header 

I can improve all the changes mentioned please assign this issue to me

### Screenshots

<img width="943" alt="Screenshot 2023-05-26 233643" src="https://github.com/Fenrir-04/Algo-Media/assets/77677724/76832578-761e-42f2-b641-d6298117a9e2">

**Comment by KOMALDEWNANI** [comment]
This is the same as Issue #3  which has already been assigned.
