### ISSUE TITLE
[FEATURE] Add YouTube-like Video Information Display to AlgoMedia

### ISSUE THREAD

**Issue by KOMALDEWNANI** [Fenrir-04/Algo-Media#87]
### Description

Addition of a feature that displays key video information, such as the video title, channel name, like count, and description, similar to how YouTube presents these details. This enhancement would significantly improve the user experience by providing important context and improving content discoverability within the application.

### Screenshots

![image](https://github.com/Fenrir-04/Algo-Media/assets/57641789/913526a9-49f5-4a2f-8b65-85368ab0e3a4)

**Comment by pratyush-ksingh** [comment]
I would like to work on this project under GSSoc'23, please assign it to me.

**Comment by pratyush-ksingh** [comment]
Hello @KOMALDEWNANI, I have sent the pull request for this issue.
