### ISSUE TITLE
Migrate AlgoMedia to YouTube APIs for Enhanced Functionality

### ISSUE THREAD

**Issue by KOMALDEWNANI** [Fenrir-04/Algo-Media#89]
### Description

In order to expand the functionality and capabilities of AlgoMedia, we propose migrating the application from using the Rapid APIs to utilizing the official YouTube APIs. By transitioning to YouTube APIs, we can leverage the wider range of endpoints and features provided by YouTube, allowing us to incorporate additional functionalities that will enhance the user experience and improve content discovery within the application.
Visit https://developers.google.com/youtube/v3/docs for more references.

**Comment by kartikayasija** [comment]
I want to work on this issue, Please assign it to me.

**Comment by KOMALDEWNANI** [comment]
Go ahead! 🚀
