### ISSUE TITLE
Adding scrollbar for left panel and for the landing page

### ISSUE THREAD

**Issue by Sameep002** [Fenrir-04/Algo-Media#9]
I want to contribute by adding this feature.

**Comment by Fenrir-04** [comment]
can you provide more details about the feature.

**Comment by Sameep002** [comment]
On the left panel where all the topics for videos are mention there we can add a scroll bar to scroll down all topics and for the right part where all the videos will be shown there scroll bar also needed when the number of videos increases it would be helpful.

**Comment by Fenrir-04** [comment]
Thanks for the feedback.
But this issue is already assigned to someone else.
