### ISSUE TITLE
[FEATURE] Implement Comment Section for AlgoMedia Videos

### ISSUE THREAD

**Issue by KOMALDEWNANI** [Fenrir-04/Algo-Media#90]
### Description

To foster engagement and facilitate user interactions, we propose adding a comment section feature to AlgoMedia, similar to the comment system used on YouTube. By introducing a comment section, users will be able to share their thoughts, opinions, and feedback directly on the platform, creating a vibrant community around the videos and enhancing the overall user experience.

Feature Requirements:
1. Comment Display: Implement a visually appealing and intuitive layout for displaying comments, ensuring they are easy to read and navigate.
2. Comment Creation: Allow users to create new comments for each video, providing a user-friendly interface for entering and submitting comments.
3. Reply to Comments: Enable users to reply to existing comments, fostering discussions and interactions within the comment section.
4. Comment Moderation: Implement a moderation system to ensure that inappropriate or spam comments can be flagged, reviewed, and potentially removed.
5. Sorting and Filtering: Provide options to sort and filter comments based on criteria such as most recent, top-rated, or user-generated, allowing users to find relevant discussions quickly.

### Screenshots

![image](https://github.com/Fenrir-04/Algo-Media/assets/57641789/ac825300-1065-462a-aa3e-605646459742)

**Comment by sandeep0009** [comment]
i would like to work upon this .assign it to me

**Comment by krishna-nayak** [comment]
Hi @KOMALDEWNANI, I would also like to contribute to this issue. Since we're migrating our API ecosystem to the YouTube API, we can use this API not only for video commenting, but also for liking and disliking videos. This means we don't need to build separate services for commenting and liking. However, before doing so, we need to obtain a YouTube API OAuth 2.0 token for authorization.

**Comment by KOMALDEWNANI** [comment]
@krishna-nayak you are right, we could not implement comment section unless authentication part and Migration to new API is sorted. You can collaborate with @sandeep0009 to work on this issue.

**Comment by krishna-nayak** [comment]
Hey @sandeep0009! Let's have a discussion on how to resolve issue #90. My Discord username is **krishna-nayak#1498**, and I'd be more than happy to chat with you about it and work together to resolve the issue. Feel free to send me a message anytime!

**Comment by krishna-nayak** [comment]
Hi @KOMALDEWNANI, I want to quickly review the UI section to ensure that I don't make any mistakes. If any changes are necessary, please let me know. So far, I have only worked on the UI, and adding functionality will begin soon. 

## Screen Recording  📸 :
https://github.com/Fenrir-04/Algo-Media/assets/72739429/26b682c3-74d3-4cad-bf60-3d8aaa8cbea7

## Screenshot  📸 :
<img width="1440" alt="Screenshot 2023-05-29 at 4 39 50 PM" src="https://github.com/Fenrir-04/Algo-Media/assets/72739429/6de6aa69-f138-4435-bd59-10624fc99756">

**Comment by KOMALDEWNANI** [comment]
Good work! 🚀
