### ISSUE TITLE
[FEATURE] Authentication - Login/Signup

### ISSUE THREAD

**Issue by kartikayasija** [Fenrir-04/Algo-Media#93]
### Description

The project lacks authentication, Authentication would be useful for displaying history, subscriptions etc.

It can be implemented by using bcrypt and JWT token.

### Additional information

Please assign this issue to me.

**Comment by krishna-nayak** [comment]
I don't think we need to separate authentication by using bcrypt and JWT tokens. Instead, we can use the YouTube API OAuth 2.0 token for authorisation.

**Comment by kartikayasija** [comment]
@krishna-nayak The Authentication and Authorisation are two different things. Authentication (Login) will be required if we want to implement features like history, subscriptions, liked videos, comments, etc.

**Comment by kartikayasija** [comment]
sure @yashvardhan-verma

**Comment by KOMALDEWNANI** [comment]
Hey, @kartikayasija could you explain how you would be implementing this? Would you add the authentication and authorization with Google via Oauth 2.0 or create your own backend, store users and generate jwt?

**Comment by kartikayasija** [comment]
I think using jwt token would be fine.

**Comment by yashvardhan-verma** [comment]
@kartikayasija so you are creating a backend ?

**Comment by krishna-nayak** [comment]
Hello there! It is possible to obtain an OAuth 2.0 Access Token on client side without a backend server. But It is not recommended to do so, as it can expose sensitive information. Link: [oauth2-without-client-secret-possible-phishing](https://stackoverflow.com/questions/44595392/oauth2-without-client-secret-possible-phishing)

**Comment by kartikayasija** [comment]
We can do Authentication without backend using Firebase.

**Comment by krishna-nayak** [comment]
Yes, we can use Firebase as a backend, and it supports OAuth 2.0, which will allows us to obtain an access token for the YouTube API as well. Well done 👏  @kartikayasija. I have just tested it out.

**Comment by kartikayasija** [comment]
Yes, I'll integrate it by today.
