### ISSUE TITLE
[FEATURE] Infinite Scrolling

### ISSUE THREAD

**Issue by ahegde3** [Fenrir-04/Algo-Media#95]
### Description

Feature for user to scroll across all the recommendation. We can use pagination to make the api fetch a fix number of videos and user scrolls down a next set of videos will be fetched

Let me know do you want to include this feature .

Please assign me this issue under GSSOC'23

**Comment by yashvardhan-verma** [comment]
@ahegde3 start working

**Comment by kartikayasija** [comment]
Can I work on this Issue if this is not solved till now?

**Comment by ahegde3** [comment]
@kartikayasija I am working on it.
